package com.child1.activity_service.Model;



public enum ActivitType {

    RUNNING, WALKING , SWIMING ,
    WEIGHT_TRAINING, CYCLING, YOGA,
    HIIT, DANCE, BOXING, PILATES, AEROBICS,
    STRETCHING, MARTIAL_ARTS, ROCK_CLIMBING, HIKING,
    SKATING, SKIING, SNOWBOARDING, SURFING, GYMNASTICS,
    CROSS_TRAINING
}
